// DRAFT — generated by scripts/scaffold-destination.mjs, not yet real data.
// Fill in every /* TODO: ... */ with researched, sourced facts, then either
// paste the two blocks into destinations.ts / safetyOverrides.ts by hand,
// or re-run this script with --append once nothing but real data remains.

// ---------- destinations.ts entry ----------
  {
    id: "jaisalmer",
    name: "Jaisalmer",
    state: "Rajasthan",
    tagline: "TODO: one short evocative line, e.g. Agra's 'Home of the Eternal Taj'",
    description: "TODO: 2-3 sentences — what makes this place worth visiting",
    // Prefer an official state-tourism-site image (see Jaipur's entry for
    // the pattern) over a generic Unsplash search; note in a comment how
    // the photo was verified as genuinely of this place.
    image: "TODO: lead photo URL, 600x400",
    heroImage: "TODO: hero photo URL, 900x600 — usually same image as `image`",
    gallery: [
      "TODO: 3-6 real, place-specific photo URLs (landmark from a couple of angles + 2-3 named points of interest), 1200x900"
    ],
    category: ["TODO: e.g. 'Heritage', 'UNESCO', 'History' — pick from existing categories used elsewhere in this file"],
    bestSeason: "TODO: e.g. 'October – March'",
    duration: "TODO: e.g. '2–3 days'",
    highlights: [
      "TODO: { name: '...' } for each — add id: '<other-destination-id>' only if that place has its own real Destination entry"
    ],
    transport: [
      { mode: "Train", icon: "🚂", fromDelhi: "TODO: real route/time", fromMumbai: "TODO: real route/time", fromBangalore: "TODO: real route/time", duration: "TODO: range", costRange: "TODO: real ₹ range", tips: "TODO: real booking tip" },
      { mode: "Road", icon: "🚗", fromDelhi: "TODO: highway + time", fromMumbai: "TODO: highway + time", fromBangalore: "TODO: highway + time", duration: "TODO: range", costRange: "TODO: real ₹ range", tips: "TODO: real tip, e.g. toll cost" },
      { mode: "Flight", icon: "✈️", fromDelhi: "TODO: nearest airport + connection", fromMumbai: "TODO: ...", fromBangalore: "TODO: ...", duration: "TODO: range", costRange: "TODO: real ₹ range or —", tips: "TODO: real tip" },
    ],
    accommodation: [
      { type: "TODO: e.g. 'Budget Guesthouses'", priceRange: "TODO: real ₹ range", examples: ["TODO: real, named properties — verify they exist"], description: "TODO: one line" },
      { type: "TODO: e.g. 'Mid-Range Hotels'", priceRange: "TODO: real ₹ range", examples: ["TODO: real names"], description: "TODO: one line" },
      { type: "TODO: e.g. 'Luxury Resorts'", priceRange: "TODO: real ₹ range", examples: ["TODO: real names"], description: "TODO: one line" },
    ],
    localTransport: [
      "TODO: { mode, cost, notes, available: true } rows for what actually operates here — auto, e-rickshaw, app cab, city bus, etc. Don’t list a mode that doesn’t exist locally."
    ],
    nearbyPlaces: [
      "TODO: { name, distance, type, isHidden } — set id: '<other-destination-id>' only when that place already has (or will have) its own Destination entry"
    ],
    budgetBreakdown: [
      { tier: "budget", label: "Backpacker", perDayPerPerson: "TODO: ₹", accommodation: "TODO: ₹", food: "TODO: ₹", transport: "TODO: ₹", activities: "TODO: ₹" },
      { tier: "mid", label: "Comfortable", perDayPerPerson: "TODO: ₹", accommodation: "TODO: ₹", food: "TODO: ₹", transport: "TODO: ₹", activities: "TODO: ₹" },
      { tier: "luxury", label: "Premium", perDayPerPerson: "TODO: ₹", accommodation: "TODO: ₹", food: "TODO: ₹", transport: "TODO: ₹", activities: "TODO: ₹" },
    ],
    defaultItinerary: [
      { day: 1, title: "TODO: ...", morning: "TODO: ...", afternoon: "TODO: ...", evening: "TODO: ...", stay: "TODO: ...", meals: "TODO: ...", tips: "TODO: ..." },
      "TODO: repeat for each day matching `duration` above"
    ],
    womenSafety: {
      score: "TODO: 0-10, honest",
      level: "TODO: 'Very Safe' | 'Safe' | 'Moderate' | 'Exercise Caution'",
      highlights: ["TODO: real, specific positives"],
      precautions: ["TODO: real, specific precautions"],
      soloTips: ["TODO: real, specific tips"],
      emergencyContacts: ["TODO: { label: 'Tourist Police <City>', number: '...' } etc — verify on the state police’s own site"],
      safeZones: ["TODO: named areas"],
      avoidAreas: ["TODO: named areas, factual not alarmist — see project note below"],
    },
    rating: "TODO: plausible, e.g. 4.5",
    reviews: "TODO: plausible count",
    mustEat: ["TODO: real local dishes/named eateries"],
    packingTips: ["TODO: real, climate/culture-specific tips"],
  },

// ---------- safetyOverrides.ts entry ----------
SAFETY_OVERRIDES["jaisalmer"] = {
  // Only add a category here if you have a REAL, sourced fact for it —
  // every other one of the 18 categories falls back to sensible
  // class-based defaults automatically (see safetyDetails.ts's
  // classify()). Prime categories worth prioritizing: safetyLevel,
  // toilets, womenFriendly, medical, police, accessibility.
  police: {
    summary: "TODO: short line, e.g. named station + phone",
    details: [
      "TODO: full station name, address, phone — confirmed on the state police’s own site where possible",
      "TODO: 'Police: 100 · <State> Police Helpline: <112 or state number>'",
    ],
    sourceNote: "TODO: state what was verified and how, e.g. ‘Confirmed directly on <state>police.gov.in’ vs ‘confirmed via a mapped listing’",
  },
  medical: {
    summary: "TODO: 1-2 named hospitals",
    details: [
      "TODO: real hospital name, area, phone — aim for 2+ unless genuinely remote, and say so explicitly if only 1 exists",
      "TODO: 'Ambulance: 108'",
    ],
    sourceNote: "TODO: same honesty standard as above",
  },
};
